"""empty message

Revision ID: 84789556fe4d
Revises: c8b716e8e8f1
Create Date: 2017-08-02 14:42:36.306421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84789556fe4d'
down_revision = 'c8b716e8e8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personne')
    # ### end Alembic commands ###
